version: '3'
services:
  # db:
  #   platform: linux/x86_64 # M1チップ対応のため追記
  #   image: mysql:5.7
  #   restart: always # 起動が遅いため、再起動させる
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: django-db
  #     MYSQL_USER: django
  #     MYSQL_PASSWORD: django
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  web:
    build: .
    shm_size: '3g'
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "4444:4444"
      - "5901:5900"
      - "7900:7900"
    # depends_on:
    #   - db